sonar.projectKey=fashionshop-kcpm
sonar.organization=fashionshop-kcpm

sonar.projectName=FashionShop
sonar.projectVersion=1.0

# Source code
sonar.sources=fashionshop-api/app,fashionshop-web/src,fashionshop-admin/src

# Tests
sonar.tests=fashionshop-api/tests,tests/api,tests/e2e

# Exclusions
sonar.exclusions=\
  **/node_modules/**,\
  **/vendor/**,\
  **/storage/**,\
  **/bootstrap/cache/**,\
  **/public/**,\
  **/*.min.js,\
  **/dist/**,\
  **/build/**,\
  
  tests/node_modules/**
  

# PHP
sonar.php.version=8.3
sonar.php.coverage.reportPaths=fashionshop-api/coverage.xml

# JavaScript
sonar.javascript.file.suffixes=.js,.jsx

sonar.sourceEncoding=UTF-8
sonar.python.version=3.10,3.11,3.12